{% set name = "acme-tiny" %}
{% set version = "5.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: b3ce195583dc2f13a7c6fa90052f8ab349b232dbc267ad9cbf4728eaed84ddd8

build:
  number: 0
  noarch: python
  entry_points:
    - acme-tiny = acme_tiny:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools_scm
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - acme_tiny
  commands:
    - pip check
    - acme-tiny --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/diafygi/acme-tiny
  summary: A tiny script to issue and renew TLS certs from Let's Encrypt
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fuglede
